### PR TITLE
Energy spectr

### PR DESCRIPTION
**Pull request by andiresch**
Major change: added option to score fluence differential in LET either to the material of the geometry attached to or/and to a user defined material

Minor changes: few bug fixes/code improvements

### CODE REVIEW

**Comment by dsarrut** [comment]
Hi Andreas, 
sorry, could you please resolve the conflicting files? (a lot of commits those days ...)

thanks, 
David

**Comment by andiresch** [comment]
Hi David,

is it resolved now? I pulled the upstream/develop into my branch. 

cheers,
Andreas

**Comment by tbaudier** [comment]
Hi @andiresch ,

I removed your merge commit to have a clean history
I added a style commit to avoid trailling whitespace

**Comment by dsarrut** [comment]
thanks !

**Pull request merged**
