### PR TITLE
Toward 9.3

### PR DESCRIPTION
**Pull request by kochebina**
The dockerfile for 9.3 is coming

### CODE REVIEW

**Comment by BishopWolf** [comment]
Let me know when this version is final to push the docker image

**Comment by BishopWolf** [comment]
This PR needs https://github.com/OpenGATE/Gate/pull/554 to be integrated first

**Comment by tbaudier** [comment]
I need to do before merge this PR
 - [x] update data tests with new geant4 version
 - [x] do not execute t9 because gaga is depreceated (like t14)
 - [x] integration of gt_digi_mac_converter and release gatetools
 - [x] merge https://github.com/OpenGATE/GateBenchmarks/pull/84 with reference output
 
Then
 - [x] Create PR for benchmark with adapted benchmarks to the new digitizer (https://github.com/OpenGATE/GateBenchmarks/pull/89)
 - [x] Test locally this new PR with PR of digitizer
         :heavy_check_mark: t1_edep_profiles
         :heavy_check_mark:  t2_edep_vox
         :heavy_check_mark: t3_range_e+
         :heavy_check_mark: t4_necr
         :heavy_check_mark: t5_pet
         :heavy_check_mark: t6_dpk
         :heavy_check_mark: t7_garf
         :heavy_check_mark: t8_LETActor
         :heavy_check_mark: t10_SpectroGamma
         :heavy_check_mark: t11_EMField
         :heavy_check_mark: t12_tessellated_volume
         :heavy_check_mark: t13_phsp 
         :heavy_check_mark: t15_optical
         :heavy_check_mark: t16_decay
         :heavy_check_mark: t17_extended_source
         :heavy_check_mark: t18_movement_benchmark
         :heavy_check_mark: t19_acollinearity
         :heavy_check_mark: t20_digi_adder
         :heavy_check_mark: t22_merged_actor
         :heavy_check_mark: t23_digi_readout
         :heavy_check_mark: t26_CoinSorter
         :heavy_check_mark: t27_Hits_2SD
         :heavy_check_mark: t28_Singles_2SD
         :heavy_check_mark: t29_optical_digi
 - [ ] Merge https://github.com/OpenGATE/Gate/pull/571 with benchmark, contrib, doc https://github.com/OpenGATE/Gate/pull/579 , ...
 - [ ] Update release note (https://github.com/OpenGATE/Gate/blob/develop/release_notes/v9.2.txt) 

Then tag to 9.3 and after
 - [ ] Update docker image
 - [ ] Update VM

**Comment by tbaudier** [comment]
:x: t4_necr
```
['\''output'\'']
Prompt events    0 	(all coincidences)
Delayed events   0  	(approximation of the number of random events)
Random events    0 	(including noise event)
Scattered events 0
Trues events     0
Prompt rate     0 cps    -> 100.00%   (tol 10.0%)
Delayed rate    0 cps     -> 100.00%   (tol 10.0%)
Random rate     0 cps    -> 100.00%   (tol 10.0%)
Scattered rate  0 cps    -> 100.00%   (tol 25.0%)
Trues rate      0 cps     -> 100.00%   (tol 25.0%)
Cylindrical phantom radius = 102 mm
Cylindrical phantom height = 700 mm
Cylindrical phantom volume = 22879.59 mL
Total activity             = 1787.91 MBq
Activity concentration     = 78.144 kBq.mL-1
Simulation duration        = 0.0003 sec
ScatterFraction            = nan %   <-> 39.56  -> nan%  (tol 10.00%)
NECR                       = nan  <-> 75216 cps
NECR Difference is         = nan % (tol 30%)
Test :  False

```

:x: t18_movement_benchmark
```
[G4-cerr] ***** COMMAND NOT FOUND </gate/output/ascii/setOutFileEWindowFlag 0> *****
```

**Pull request merged**
