### PR TITLE
Torch yes cuda no

### PR DESCRIPTION
**Pull request by djboersma**
This PR tries to fix issue #320 and the issues that PR #318 tried to address: some struggles between GateLib, cmake versions and libtorch.

In other words: we want to be able to build and link Gate with old cmake (versions older than 3.12) and new cmake (version 3.12 and newer). We also want to be able to build Gate with and without "libtorch".
I tested these 2x2 combinations with this branch and for me it works. Please try on more systems before merging. In order to make a "libtorch" build possible, I needed to add a cmake line to add the include directories. This is necessary if libtorch is not installed in a system directory (i.e. not under `/usr` or `/usr/local`).

Also note a  kind of major tangential issue: the `CMakeLists.txt` file had inconsistent conditional code for building with/without CUDA. Since the CUDA/GPU code has been without maintainer for quite a long time, rather than fixing the inconsistency it seems better to finally remove the GPU code altogether (after a long deprecation period). This affects:
* the references in the `CMakeLists.txt` file
* the `source/gpu` directory (with CUDA kernel code)
* several dozen purely GPU-specific classes
* references in the rest of Gate to the GPU-specific code.

All that is gone now. This hurts a bit, because GPU computing is so tantalizingly cool and it's clear that a lot of effort went into this code. But it's better this way, I think. The code is still available here on GitHub, so if anyone would like to do a new try with CUDA, then maybe some of the old code can serve as learning material. However, the CUDA library today is very different from CUDA back when this code was written. Also, the original authors have stated that they were not happy with the overall design: the Gate/Geant4 environment does not allow proper GPU parallelism, if I understood them correctly. So it's likely that any new attempts to use CUDA in Gate have to be very different.

### CODE REVIEW

**Comment by tbaudier** [comment]
The commit https://github.com/OpenGATE/Gate/pull/322/commits/169db37125ef85b4e1e6481f798cd8a8cf62bcac introduces a lot of Warnings from Torch
https://my.cdash.org/buildSummary.php?buildid=1787793

**Comment by djboersma** [comment]
> 
> 
> The commit [169db37](https://github.com/OpenGATE/Gate/commit/169db37125ef85b4e1e6481f798cd8a8cf62bcac) introduces a lot of Warnings from Torch
> https://my.cdash.org/buildSummary.php?buildid=1787793

Yes, I noticed that. I first thought that was more of a problem for torch than for us, because when I looked on my terminal (compiling with gcc 9.2) there were lots of warnings about unused variables. But in your link I see now that there are issues with which C++ standard we use. I wonder if this will be fixed if we simply remove line 300, `set(CMAKE_CXX_STANDARD 11)`. I think that that line was originally introduced to stop users from trying to compile with **too old** compilers (gcc 4.2 and older, I think) which did not support c++11 yet.  The intention was **not** to prohibit c++ standards 14 and 17.
So let me remove that line and see if that reduces the compile warning flood a bit.

**Comment by djboersma** [comment]
Actually, I wonder why all these warnings only popped up with my commit. The only torch-related thing that I did was to make sure that the torch include directory would be included in the `-Iincdir` flags (because without it, it didn't compile for me when I set `GATE_USE_TORCH` to `ON`). The warnings should have been there on your test system before as well, because on your test systems it should still `#include` the same header files, before and after my commit.

Anyway. I think that my commit dams in the flood of warnings a little bit, also by using GCC pragmas to disable certain warnings when including the torch headers. This may not help with other compilers than GCC, such as Clang. And there are still many warnings left, with assert-like macros that are apparently `#define`d with a boolean test and a message implemented through variadic parameters, but in the code often only the boolean expression is given and the message part is left out.

**Comment by djboersma** [comment]
Aha, now the Azure build tests "Linux_Torch" and "MacoS_Torch" have finished and it looks like there are "0 errors / 0 warnings". That is nice. I see that on those systems you use gcc 7.4, while I am using gcc 9.2, which is apparently way more pedantic. I guess it might be useful to mention in the release notes that gcc 7.4 was used as a default compiler, and that with newer compilers such as gcc 9.2 the build may be quite noisy.

**Comment by djboersma** [comment]
Yay! :)

**Pull request merged**
