### PR TITLE
Dev em fields

### PR DESCRIPTION
**Pull request by fpadilla84**
Dear David,

I just redo the new branch from the last develop version update from today and include a very simple running example. Hopefully is now easier for you to spot all the differences. Sorry for the troubles during the last PR, and please let me know if you need something else from my side,

BR,

Fatima

### CODE REVIEW

**Comment by dsarrut** [comment]
Thanks for this new PR! 

It is almost ok to be merged, except that the example you provide must be submitted to the GateContrib repository, not this one. Please:
1 - provide a PR in this repo with changes to the source code only (not with the example)
2 - provide another PR in GateContrib repo with the example (in the [dosimetry](https://github.com/OpenGATE/GateContrib/tree/master/dosimetry) example). Be careful that you need to pull first and initialize the LFS (git lfs install) because you include some binary files. 

thanks!
David

**Comment by dsarrut** [comment]
(Do not hesitate to contact me if you need help)

**Comment by fpadilla84** [comment]
Hi David,
I already remove the Example directory from the branch, hopefully everything will be fine now. 
Thanks a lot,
Fatima

**Comment by tbaudier** [comment]
Hi @fpadilla84 

I removed your commits about the example to clean the history. I did a pull request for this example here: https://github.com/OpenGATE/GateContrib/pull/40

I add a new commit to correct the license

**Comment by dsarrut** [comment]
very good, thanks a lot Fatima and Thomas !

**Pull request merged**
