### PR TITLE
Fix issue #203 - Dose by region flag was not initialized.

### PR DESCRIPTION
**Pull request by SimonRit**
I used to valgrind to fix this. mDoseByRegionsFlag was not initialized so issue #203 was randomly occuring. With mDoseByRegionsFlag set to true, I had the same error message. I added an error message to make the error more explicit but set mDoseByRegionsFlag to false by default.

### CODE REVIEW

**Comment by dsarrut** [comment]
Awesome, thanks !!

**Comment by uhqd** [comment]
Congratulations for fixing this bug !
Hope this will be in the 8.2 release... Thank you very much anyway. 
Small question : there is an internal discussion here to decide where to write the visualisation command line : at its historic place (i.e. at the begining of the .mac) or after the initialize command. Some of us (the religious ones) think that this issue was responsible of this bug. But if I understand well, we can let the visu line at the beginning of the file (please answer, we bet a beer on this issue...). Again thank you.

**Comment by SimonRit** [comment]
No, this issue was not responsible of this bug. The code was testing a boolean which was never set. So it basically relied on what was in memory. Depending on what was done before with the memory now occupied by the boolean, it could have been true (non zero) or false (zero). So you could have different behaviors by switching the order of the commands but that was by luck.
As for the order of the commands, I never know when one is allowed to do what. So I'll let someone else answer that question. Yet, I have always set visu before init.
BTW, I like beer too. Cheers! Simon

**Comment by uhqd** [comment]
Ok thank you. Wait you for a beer here...Cheers

**Pull request merged**
