### PR TITLE
WIP: Towards Geant4.11.0

### PR DESCRIPTION
**Pull request by dsarrut**
(from @cpommranz)

Warning: Right now, this is not a fix, but only a collection of problems
we have to solve to allow for Gate compilation against Geant4.11.0.
There might be additional affecting Geant4 changes, that do not lead to
compilation errors. We have to investigate.

### CODE REVIEW

**Comment by BishopWolf** [comment]
Just a warning I have every time
```
-------- WWWW ------- G4Exception-START -------- WWWW -------
*** G4Exception : HAD_RDM_676
      issued by : G4RadioactiveDecayBaseMessenger
This command is valid but deprecated and will be replaced with the command:
/process/had/rdm/verbose in the next major release, Geant4 version 11.0
*** This is just a warning message. ***
-------- WWWW -------- G4Exception-END --------- WWWW -------
```

**Comment by tbaudier** [comment]
Hi @cpommranz 

I saw your last commit about ROOT.
I think I succeed to update ROOT on my side:
https://github.com/OpenGATE/Gate/pull/477

The macOS machines were updated on Github Actions leading to build failure. 
So I updated ROOT to be able to compile again. And I needed to compile everything in c++17 too.

**Comment by tbaudier** [comment]
Thank you, it's almost done

I see an error with RTK:
```
[ 17%] Building CXX object CMakeFiles/GateLib.dir/source/digits_hits/src/GateFluenceActorMessenger.cc.o
/Users/runner/work/Gate/Gate/source/digits_hits/src/GateFixedForcedDetectionActor.cc:177:5: error: unknown type name 'G4PhysicsOrderedFreeVector'; did you mean 'G4PhysicsFreeVector'?
    G4PhysicsOrderedFreeVector energyHistogram = mSource->GetEneDist()->GetUserDefinedEnergyHisto();
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
    G4PhysicsFreeVector
/Users/runner/software/geant4/install/include/Geant4/G4PenelopeGammaConversionModel.hh:55:7: note: 'G4PhysicsFreeVector' declared here
class G4PhysicsFreeVector;
      ^

```
In that line https://github.com/cpommranz/Gate/blob/towards_geant4.11.0/source/digits_hits/src/GateFixedForcedDetectionActor.cc#L177
is it possible to replace G4PhysicsOrderedFreeVector by auto?

**Comment by SimonRit** [comment]
I think so. Thanks @tbaudier !

**Comment by cpommranz** [comment]
Thanks @tbaudier and @SimonRit ! G4PhysicsOrderedFreeVector was indeed removed in Geant4 v11.0 and G4SPSEneDistribution::GetUserDefinedEnergyHisto now returns a G4PhysicsFreeVector. Switched to auto.

**Comment by dsarrut** [comment]
Warning: QT visualization to check (I had issues on OSX and Linux)

**Pull request merged**
