### PR TITLE
Fluence track length

### PR DESCRIPTION
**Pull request by AndersGarpebring**
Dear Gate developers,

I have created two actors that enables measurement of Fluence and I would like to have these included in the official version of Gate. I have also created two examples that can be found in the folder TrackLengthFluenceExampes showing how the actors function. Finally, I have included some documentation that can be found in the same folder. I have attached the documentation to this pull request so you can
[Track_Length_Actors.pdf](https://github.com/OpenGATE/Gate/files/4219863/Track_Length_Actors.pdf)
 get a better picture of what I have developed.

Don't hesitate to ask if you have some questions.

Kind regards,
Anders Garpebring
anders.garpebring@umu.se

### CODE REVIEW

**Comment by dsarrut** [comment]
Hello Anders, 
this is really great, thanks! In order to be included, could you please separate it into two PRs : 
1. One PR with the source code only (no example, no pdf) in this repository. 
2. Another PR with the example only in the [GateContrib](https://github.com/OpenGATE/GateContrib) repository. Please remove all 'kde' related files/folders before. Also, pay attention that you have binary files (raw), so be sure to enable git lfs before committing those files. Also, put the pdf file in this example. 
3. Also, you can also add short documentation https://opengate.readthedocs.io/en/latest, in the [section related to actors](https://opengate.readthedocs.io/en/latest/tools_to_interact_with_the_simulation_actors.html#list-of-available-actors). To propose documentation change, click on the "edit on github" menu in the green bottom right area, it will open an editor in the github file and you will be able to provide a PR. 

Thanks a lot, this actor will be really useful, and do not hesitate to contact us if help is needed. 
David

**Comment by AndersGarpebring** [comment]
Hello David,

I have now removed the examples. I tried to get rid of the .kdev folder by changing the .gitignore. But it seems like it doesn't remove it. Anyway, just ignore the .kdev and .gitignore folders when you merge in my code. All my code is in the digital_hits folder.

I will put up my examples on the other repository you mentioned.

Best,
Anders

**Comment by tbaudier** [comment]
Hi @AndersGarpebring ,

Thank you for your modifications, I cleaned your PR doing one commit to avoid to have a dirty history with removed/bad files.

**Comment by AndersGarpebring** [comment]
Thanks! 

All is done now, or do you need something else from me?

**Comment by dsarrut** [comment]
Perfect, thanks !

**Pull request merged**
