### PR TITLE
install only the Gate binary, no (external) headerfiles/libraries

### PR DESCRIPTION
**Pull request by djboersma**
Since ages the 'make install' command has installed not only the Gate binary,
but also some random stuff from the `itk-mhd` external source directory. With this
commit that should be fixed: 'make install' will *only* install the Gate binary
in the `$CMAKE_INSTALL_PREFIX/bin` directory, nothing else.

To achieve this, I commented something out in one `CMakeLists.txt` file and set a
flag in another. This way the offending code that was
responsible for these spurious installs is still there, but it is deactivated.
If someone remembers or stumbles upon a use case in which these lines were
actually useful, then we can re-enable them with the proper conditionals. If
this does not happen within a year or so, then we can just delete this dead
code.

This commit should fix issues #75 and #123.

### CODE REVIEW

**Comment by djboersma** [comment]
@mojca , could you please check if this indeed fixes issue #123 that you reported? I checked 'make install', but I have no experience with "DESTROOT".

**Comment by mojca** [comment]
Million times better, thank you very much. But please reword the commit message before merging.

**Comment by djboersma** [comment]
sorry about that crude message. hope it's better now.

**Comment by mojca** [comment]
You need to change the commit message rather than title of this ticket

**Comment by djboersma** [comment]
I don't see a way to do edit that. I think I'll just delete this PR and resubmit.

**Comment by mojca** [comment]
`git commit --amend` and edit the message
`git push -f <wherever you push>`

**Comment by djboersma** [comment]
Cool, thanks! I think that worked. Are you OK with the new phrasing?

**Comment by mojca** [comment]
Certainly ok by me, thanks a lot.

**Pull request merged**
