### PR TITLE
 Add GateLib library (redo 0cca60010ed825ead69d1fe6b798718c83e149bb)

### PR DESCRIPTION
**Pull request by wrzof**
Avoiding static library, it fix the problem mentionned in https://github.com/OpenGATE/Gate/commit/ef4b8d981a8f2176bed1354ea65262bc6c7c5d93#commitcomment-37267735

### CODE REVIEW

**Comment by tbaudier** [comment]
Hi @wrzof 

Thank you, I did not know the Object Library.
In my case, it failed to compile on my Linux while it works on the Mac and on both for develop branch.
I had the following error:
```
In file included from /home/tbaudier/Software/Gate/rc/geant4.10.6/install/include/Geant4/G4OpenGLSceneHandler.hh:41:0,
                 from /home/tbaudier/Software/Gate/rc/gate/src_wrzof/source/geometry/include/GateImageBox.hh:32,
                 from /home/tbaudier/Software/Gate/rc/gate/src_wrzof/source/geometry/src/GateImageBox.cc:6:
/home/tbaudier/Software/Gate/rc/geant4.10.6/install/include/Geant4/G4OpenGL.hh:84:14: fatal error: qgl.h: No such file or directory
     #include <qgl.h>
              ^~~~~~~
compilation terminated.
```

To deal with this problem, I added in CMakeLists.txt [l268](https://github.com/wrzof/Gate/blob/avoid_redondant_compilation/CMakeLists.txt#L268) :
```diff
  ENDIF(GATE_USE_GPU AND CUDA_FOUND)
+ TARGET_LINK_LIBRARIES(GateLib ${Geant4_LIBRARIES} ${ROOT_LIBRARIES} ${CLHEP_LIBRARIES} ${LIBXML2_LIBRARIES} ${LIBXRL_LIBRARIES} ${LMF_LIBRARY} ${ECAT7_LIBRARY} ${TORCH_LIBRARIES} ${ITK_LIBRARIES} pthread)
  TARGET_LINK_LIBRARIES(Gate ${Geant4_LIBRARIES} ${ROOT_LIBRARIES} ${CLHEP_LIBRARIES} ${LIBXML2_LIBRARIES} ${LIBXRL_LIBRARIES} ${LMF_LIBRARY} ${ECAT7_LIBRARY} ${TORCH_LIBRARIES} ${ITK_LIBRARIES} pthread)

```

**Comment by wrzof** [comment]
Very strange, I do not understand, 
you fix a include problem with a modification of the linking step ? 

Are you sûre that the two things are related ? 

On which distribution are you working ?

**Comment by tbaudier** [comment]
> Very strange, I do not understand,
> you fix a include problem with a modification of the linking step ?

Yes I just added this line

> 
> Are you sûre that the two things are related ?

I have no idea, but with this line the compilation works and simulation works too (I recompiled from scratch every time). Do you have a suggestion to be sure that things are related?

> 
> On which distribution are you working ?

Linux - Opensuse 15.0
Linux 4.12.14-lp150.12.61-default
With Geant4 10.6

**Comment by wrzof** [comment]
I tested on a very fresh install of opensuse 15.0, and I do not have any compilation problem. 

I suspect a problem on your configuration.

**Comment by dsarrut** [comment]
thanks!

**Comment by SimonRit** [comment]
I have the same problem. Have you ever solved your problem @tbaudier? I suspect an issue with Cuda...

**Comment by SimonRit** [comment]
Actually, @djboersma removed your change with 169db37. It seems obvious to me that GateLib should be linked to the other libraries and that all the executables only need to be linked to GateLib.

**Comment by djboersma** [comment]
I hope I did that correctly. :) And the CUDA code is no longer included in Gate...

**Comment by SimonRit** [comment]
I don't know. Forget my CUDA comment, I don't think that's the issue. My main question for you @djboersma is why did you comment it?
As for the remark of @wrzof 

> y strange, I do not understand,
> you fix a include problem with a modification of the linking step ?

I checked and this seems to add some flags when compiling GateImageBox.cc.o, if I leave the line commented, I get

```
[  0%] Building CXX object CMakeFiles/GateLib.dir/source/geometry/src/GateImageBox.cc.o
/usr/bin/c++  -DG4INTY_USE_QT -DG4UI_USE_QT -DG4UI_USE_TCSH -DG4VIS_USE_OPENGL -DG4VIS_USE_OPENGLQT -DITK_IO_FACTORY_REGISTER_MANAGER -I/home/srit/src/gate/lin64/ITKFactoryRegistration -I/home/srit/src/itk/itk/Modules/Core/Mesh/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageSources/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageGradient/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageFeature/include -I/home/srit/src/itk/itk/Modules/Core/FiniteDifference/include -I/home/srit/src/itk/itk/Modules/Filtering/DisplacementField/include -I/home/srit/src/itk/itk/Modules/Registration/Common/include -I/home/srit/src/itk/itk/Modules/Numerics/Optimizers/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageNoise/include -I/home/srit/src/itk/itk/Modules/IO/XML/include -I/home/srit/src/itk/itk/Modules/IO/TIFF/include -I/home/srit/src/itk/itk/Modules/IO/RAW/include -I/home/srit/src/itk/itk/Modules/IO/Meta/include -I/home/srit/src/itk/itk/Modules/IO/CSV/include -I/home/srit/src/itk/itk/Modules/Filtering/Convolution/include -I/home/srit/src/rtk/lin64/include -I/home/srit/src/rtk/rtk/include -I/home/srit/src/rtk/lin64 -I/home/srit/src/rtk/rtk/utilities/ITKCudaCommon/include -I/home/srit/Downloads/cuda100/include -I/home/srit/src/rtk/rtk/utilities/lp_solve/colamd -I/home/srit/src/rtk/rtk/utilities/lp_solve/bfp/bfp_LUSOL/LUSOL -I/home/srit/src/rtk/rtk/utilities/lp_solve/bfp/bfp_LUSOL -I/home/srit/src/rtk/rtk/utilities/lp_solve/bfp -I/home/srit/src/rtk/rtk/utilities/lp_solve/shared -I/home/srit/src/rtk/rtk/utilities/lp_solve -I/home/srit/src/itk/itk/Modules/Filtering/Smoothing/include -I/home/srit/src/itk/itk/Modules/Filtering/FFT/include -I/home/srit/src/itk/itk/Modules/Filtering/Path/include -I/home/srit/src/itk/itk/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/home/srit/src/itk/itk/Modules/Core/SpatialObjects/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageCompose/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageStatistics/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageFilterBase/include -I/home/srit/src/itk/itk/Modules/Core/Transform/include -I/home/srit/src/itk/lin64/Modules/ThirdParty/Netlib -I/home/srit/src/itk/itk/Modules/Numerics/Statistics/include -I/home/srit/src/itk/itk/Modules/Core/ImageFunction/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageGrid/include -I/home/srit/src/itk/itk/Modules/Core/ImageAdaptors/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageIntensity/include -I/home/srit/src/itk/itk/Modules/Filtering/Thresholding/include -I/home/srit/src/itk/itk/Modules/IO/GDCM/include -I/home/srit/src/itk/itk/Modules/ThirdParty/ZLIB/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/ZLIB/src -I/home/srit/src/itk/itk/Modules/ThirdParty/Expat/src/expat -I/home/srit/src/itk/lin64/Modules/ThirdParty/Expat/src/expat -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat -I/home/srit/src/itk/lin64/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I/home/srit/src/itk/lin64/Modules/ThirdParty/GDCM -I/home/srit/src/itk/lin64/Modules/ThirdParty/VNL/src/vxl/core -I/home/srit/src/itk/lin64/Modules/ThirdParty/VNL/src/vxl/vcl -I/home/srit/src/itk/lin64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/core -I/home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/vcl -I/home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/home/srit/src/itk/lin64/Modules/ThirdParty/KWSys/src -I/home/srit/src/itk/itk/Modules/ThirdParty/KWIML/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/KWIML/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/Eigen3/src -I/home/srit/src/itk/itk/Modules/ThirdParty/Eigen3/src/itkeigen/.. -I/home/srit/src/itk/itk/Modules/Core/Common/include -I/home/srit/src/itk/lin64/Modules/Core/Common -I/home/srit/src/itk/itk/Modules/IO/ImageBase/include -I/home/srit/src/itk/lin64/Modules/IO/ImageBase -I/home/srit/src/root/lin64-install/include -I/home/srit/src/gate/lin64 -I/home/srit/src/gate/opengate/source/io/include -I/home/srit/src/gate/opengate/source/arf/include -I/home/srit/src/gate/opengate/source/geometry/include -I/home/srit/src/gate/opengate/source/physics/include -I/home/srit/src/gate/opengate/source/digits_hits/include -I/home/srit/src/gate/opengate/source/general/include -I/home/srit/src/gate/opengate/source/externals/clhep/include -isystem /home/srit/src/geant4/lin64-install/include/Geant4  -fPIC -std=c++11 -W -Wall  -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-variadic-macros -Wshadow -pipe -std=c++11 -fPIC -std=c++11  -msse2 -Wno-shadow -O3 -DNDEBUG -fno-trapping-math -ftree-vectorize -fno-math-errno -O3 -DNDEBUG   -o CMakeFiles/GateLib.dir/source/geometry/src/GateImageBox.cc.o -c /home/srit/src/gate/opengate/source/geometry/src/GateImageBox.cc
```
and if I uncomment it

```
[  0%] Building CXX object CMakeFiles/GateLib.dir/source/geometry/src/GateImageBox.cc.o
/usr/bin/c++  -DG4INTY_USE_QT -DG4LIB_BUILD_DLL -DG4UI_USE_QT -DG4UI_USE_TCSH -DG4VIS_USE_OPENGL -DG4VIS_USE_OPENGLQT -DITK_IO_FACTORY_REGISTER_MANAGER -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -I/home/srit/src/gate/lin64/ITKFactoryRegistration -I/home/srit/src/itk/itk/Modules/Core/Mesh/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageSources/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageGradient/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageFeature/include -I/home/srit/src/itk/itk/Modules/Core/FiniteDifference/include -I/home/srit/src/itk/itk/Modules/Filtering/DisplacementField/include -I/home/srit/src/itk/itk/Modules/Registration/Common/include -I/home/srit/src/itk/itk/Modules/Numerics/Optimizers/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageNoise/include -I/home/srit/src/itk/itk/Modules/IO/XML/include -I/home/srit/src/itk/itk/Modules/IO/TIFF/include -I/home/srit/src/itk/itk/Modules/IO/RAW/include -I/home/srit/src/itk/itk/Modules/IO/Meta/include -I/home/srit/src/itk/itk/Modules/IO/CSV/include -I/home/srit/src/itk/itk/Modules/Filtering/Convolution/include -I/home/srit/src/rtk/lin64/include -I/home/srit/src/rtk/rtk/include -I/home/srit/src/rtk/lin64 -I/home/srit/src/rtk/rtk/utilities/ITKCudaCommon/include -I/home/srit/Downloads/cuda100/include -I/home/srit/src/rtk/rtk/utilities/lp_solve/colamd -I/home/srit/src/rtk/rtk/utilities/lp_solve/bfp/bfp_LUSOL/LUSOL -I/home/srit/src/rtk/rtk/utilities/lp_solve/bfp/bfp_LUSOL -I/home/srit/src/rtk/rtk/utilities/lp_solve/bfp -I/home/srit/src/rtk/rtk/utilities/lp_solve/shared -I/home/srit/src/rtk/rtk/utilities/lp_solve -I/home/srit/src/itk/itk/Modules/Filtering/Smoothing/include -I/home/srit/src/itk/itk/Modules/Filtering/FFT/include -I/home/srit/src/itk/itk/Modules/Filtering/Path/include -I/home/srit/src/itk/itk/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/MetaIO/src/MetaIO/src -I/home/srit/src/itk/itk/Modules/Core/SpatialObjects/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageCompose/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageStatistics/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageFilterBase/include -I/home/srit/src/itk/itk/Modules/Core/Transform/include -I/home/srit/src/itk/lin64/Modules/ThirdParty/Netlib -I/home/srit/src/itk/itk/Modules/Numerics/Statistics/include -I/home/srit/src/itk/itk/Modules/Core/ImageFunction/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageGrid/include -I/home/srit/src/itk/itk/Modules/Core/ImageAdaptors/include -I/home/srit/src/itk/itk/Modules/Filtering/ImageIntensity/include -I/home/srit/src/itk/itk/Modules/Filtering/Thresholding/include -I/home/srit/src/itk/itk/Modules/IO/GDCM/include -I/home/srit/src/itk/itk/Modules/ThirdParty/ZLIB/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/ZLIB/src -I/home/srit/src/itk/itk/Modules/ThirdParty/Expat/src/expat -I/home/srit/src/itk/lin64/Modules/ThirdParty/Expat/src/expat -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary -I/home/srit/src/itk/itk/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat -I/home/srit/src/itk/lin64/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I/home/srit/src/itk/lin64/Modules/ThirdParty/GDCM -I/home/srit/src/itk/lin64/Modules/ThirdParty/VNL/src/vxl/core -I/home/srit/src/itk/lin64/Modules/ThirdParty/VNL/src/vxl/vcl -I/home/srit/src/itk/lin64/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -I/home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/core -I/home/srit/src/itk/itk/Modules/ThirdParty/KWIML/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/KWIML/src -I/home/srit/src/itk/lin64/Modules/ThirdParty/Eigen3/src -I/home/srit/src/itk/itk/Modules/Core/Common/include -I/home/srit/src/itk/lin64/Modules/Core/Common -I/home/srit/src/itk/itk/Modules/IO/ImageBase/include -I/home/srit/src/itk/lin64/Modules/IO/ImageBase -I/home/srit/src/root/lin64-install/include -I/home/srit/src/gate/lin64 -I/home/srit/src/gate/opengate/source/io/include -I/home/srit/src/gate/opengate/source/arf/include -I/home/srit/src/gate/opengate/source/geometry/include -I/home/srit/src/gate/opengate/source/physics/include -I/home/srit/src/gate/opengate/source/digits_hits/include -I/home/srit/src/gate/opengate/source/general/include -I/home/srit/src/gate/opengate/source/externals/clhep/include -isystem /home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/vcl -isystem /home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/v3p/netlib -isystem /home/srit/src/itk/lin64/Modules/ThirdParty/KWSys/src -isystem /home/srit/src/itk/itk/Modules/ThirdParty/Eigen3/src/itkeigen/.. -isystem /home/srit/src/geant4/lin64-install/include/Geant4 -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtOpenGL -isystem /home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/core/vnl/algo -isystem /home/srit/src/itk/itk/Modules/ThirdParty/VNL/src/vxl/core/vnl  -fPIC -std=c++11 -W -Wall  -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-variadic-macros -Wshadow -pipe -std=c++11 -fPIC -std=c++11  -msse2 -Wno-shadow -O3 -DNDEBUG -fno-trapping-math -ftree-vectorize -fno-math-errno -O3 -DNDEBUG   -fPIC -std=gnu++11 -o CMakeFiles/GateLib.dir/source/geometry/src/GateImageBox.cc.o -c /home/srit/src/gate/opengate/source/geometry/src/GateImageBox.cc
```
so it does more than changing the linking... I have not followed why there are now 5 times more exe in Gate, I don't know exactly what's an object library, I don't understand why there is a [specific GL section](https://github.com/OpenGATE/Gate/blob/develop/CMakeLists.txt#L79-L83) in the CMakeLists.txt, so I'm giving up on this, it's too complicated for me.

**Comment by djboersma** [comment]
Hi @SimonRit , I do not remember exactly. It's a while ago. It's important that we clean up & modernize our `CMakeLists.txt`, so I should have documented better what I tried and how it failed for me.

I think you are referring to line 262 in my commit:
https://github.com/OpenGATE/Gate/commit/169db37125ef85b4e1e6481f798cd8a8cf62bcac#diff-af3b638bc2a3e6c650974192a53c7291R262
It looks like I have actually tried to do it the way you discribe: add all those libraries to GateLib and then all executables should inherit the libraries from GateLib. But apparently it didn't work for me. I wonder if it failed in all cases, or only if I tried to use the LMF and ECAT libraries as well.

Concerning OpenGL: note that "policy 0072" (set in line 6) is also related to OpenGL. It *should* affect very few users, only those who for some reason have two different OpenGL installations on their system and CMake needs that policy to choose between the two. Adding this policy setting helped me to get rid of a lot of very noisy warnings on my bleeding edge test machine (with two different GPUs). As I understood it, it should have no effect at all on the majority of systems, with just one unambiguous OpenGL installation; but if there are weird problems with including and linking GL, then removing that policy setting is one thing that could be tried.

**Comment by wrzof** [comment]
@SimonRit 

>  it does more than changing the linking... 

You are right, according to the documentation (https://cmake.org/cmake/help/latest/command/target_link_libraries.html#linking-object-libraries), `TARGET_LINK_LIBRARIES` on `OBJECT library`  can inject some dependencies. It's not very intuitive.. 

So if you replace 

> TARGET_LINK_LIBRARIES(Gate ...

by 

> TARGET_LINK_LIBRARIES(GateLib  ...

It is compiling for you ?

**Comment by SimonRit** [comment]
Yes if I add a dependency to GateLib for Gate, see #337... Can you test if you see a pb with this PR?

**Pull request merged**
