### PR TITLE
CoincidenceDigiMaker bug corrected

### PR DESCRIPTION
**Pull request by kochebina**
Bug correction will be visible for CoincidenceSorters with policies:
keepIfOnlyOneGood
keepIfAnyIsGoof
keepIfAllAreGoods
killAll

### CODE REVIEW

**Comment by tbaudier** [comment]
Can you redo your commit please because you commited the build folder called "bin". Thank you

**Comment by kochebina** [comment]
Closed by mistake

**Comment by tbaudier** [comment]
Waiting for the benchmark

**Comment by tbaudier** [comment]
Benchmark done with https://github.com/OpenGATE/GateBenchmarks/actions/runs/4004079653/jobs/6874253084#step:6:14106

**Pull request merged**
