### PR TITLE
Adding visualization in docker solution

### PR DESCRIPTION
**Pull request by BishopWolf**
Solution proposed in https://github.com/OpenGATE/Gate/issues/553 by @ignacio-scarinci

### CODE REVIEW

**Comment by BishopWolf** [comment]
@dsarrut @tbaudier  you shall rebuild all docker images with this change, so all images can display visualization

**Comment by dsarrut** [comment]
thanks a lot Alex! We will try this in the following weeks, thanks

**Comment by ignacio-scarinci** [comment]
Hi, 

The proposed solution works flawlessly on Linux.

However, on macOS, there is a bug in xQuartz (https://github.com/XQuartz/XQuartz/issues/144) which is easily fixed with the following command:

`defaults write org.xquartz.X11 enable_iglx -bool YES`

**Comment by tbaudier** [comment]
Thank you, I merged. The next Docker images will integrate the modification.

**Pull request merged**
